stages:
  waiting:
    name: "Ожидание"
  pre-start:
    name: "Подготовка"
  start:
    name: "Начало игры"
    title: "Игра началась"
  mining:
    name: "Майнинг"
    title: "Майнинг фаза"
  narrowing:
    name: "Сужение"
    title: "Карта сужается"
  nether-open:
    name: "Открытие ада"
    title: "Ад открылся"
  end-open:
    name: "Открытие энда"
    title: "Энд открылся"
  close:
    name: "Финал"
  stop:
    name: "Конец"
